#!/usr/bin/env bash
set -eo pipefail

NIX=$(realpath "$(command -v nix)")
NIX_STORE_PATH=${NIX%/bin/nix}
NIX_REF=("${@:-$NIX_STORE_PATH}")

usage() {
  echo >&2 "Usage: upgrade-nix-daemon [ NIX_REF ]

Arguments:

  NIX_REF       URI referencing the nix package, defaults to store path of nix
                in current shell environment
"
  exit 1
}

echo  >&2 "Upgrade nix for root user/daemon to $NIX_STORE_PATH:"
sudo "$NIX" profile list
echo -n >&2 "Type number of profile to replace for root user (empty to not remove a profile): "
read -r answer
if [[ -n $answer ]]; then
  sudo "$NIX" profile remove "$answer"
fi

echo >&2 "installing nix profile"
sudo "$NIX" profile install "${NIX_REF[@]}"

echo >&2 "restarting nix-daemon"
if command -v systemctl >/dev/null 2>&1; then
  # On Linux with systemd
  sudo systemctl daemon-reload
  sudo systemctl enable --now nix-daemon
  sudo systemctl restart nix-daemon
elif command -v launchctl >/dev/null 2>&1; then
  # On MacOS
  sudo launchctl stop org.nixos.nix-daemon
  sudo launchctl start org.nixos.nix-daemon
else
  echo >&2 "Warning: Couldn't detect how to restart nix-daemon"
  echo >&2 "You will have to manually restart nix-daemon for configuration changes to take effect"
fi
