#!/bin/bash
set -e

NIX=$(command -v nix)
NIX_REF=("${@:-nix}")

usage() {
  echo >&2 "Usage: upgrade-nix FLAKE_REFERENCE_URI

Arguments:

  FLAKE_REFERENCE_URI   A flake compatible URI which defaults to flake registry
                        with name \"nix\".
"
  exit 1
}

echo  >&2 "Upgrade nix CLI for current user:"
"$NIX" profile list
echo -n >&2 "Type number of profile to replace for current user (empty to not remove a profile): "
read -r answer
if [[ -n $answer ]]; then
  "$NIX" profile remove "$answer"
fi

NIX_REF+=("--priority" "0")

"$NIX" profile install "${NIX_REF[@]}"


echo  >&2 "Upgrade nix for root user/daemon:"
sudo "$NIX" profile list
echo -n >&2 "Type number of profile to replace for root user (empty to not remove a profile): "
read -r answer
if [[ -n $answer ]]; then
  sudo "$NIX" profile remove "$answer"
fi

echo >&2 "installing nix profile"
sudo "$NIX" profile install "${NIX_REF[@]}"
echo >&2 "reloading systemd configs"
sudo systemctl daemon-reload
echo >&2 "restarting nix-daemon"
sudo systemctl restart nix-daemon
